application:
  shortName: ApicurioRegistry
  url: http://registry-app-inmemory.apps.ci420.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
  googleCloudStorage:
    bucketName: secaut-bucket
    directory: apicurio-registry
    keyFile: /home/runner/work/_temp/gcs-key.json
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: http://registry-app-inmemory.apps.ci420.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
